version: '3.7'

services:
  fake-quotes-svc--emit-websocket:
    image: docker.io/goforbroke1006/fake-quotes-svc:latest
    command: [ "emit", "websocket" ]
    volumes:
      - "./config.yaml:/app/config.yaml"
    ports:
      - 18081:8080

  redis:
    image: "redis:alpine"

  py:
    build: .
    command: python /code/combiner.py
    environment:
      - URI=ws://fake-quotes-svc--emit-websocket:8080/ws
    depends_on:
      - redis
      - fake-quotes-svc--emit-websocket
